name: CI

on: 
  push:
    branches:    
      - main 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install Dependencies
      run: |
        cd courier
        npm install

    - name: Test
      run: |
        cd courier
        npm run test-coverage 
      