name: CI

on: 
  push:
    branches:    
      - main 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: npm install
      run: |
        cd courier
        npm install
   
    - name: npm test
      run: |
        cd courier
        npm test 
      